# Note: this is the configuration file used by Miniconda/Anaconda to create a Python environment
# with the list of packages below that were used to run our own experiments.
#
# To create such an environment, use:
#    conda env create -f environment.yml
#
# Then, to activate it in a terminal, use:
#    conda activate hardpicks-dev

name: hardpicks-dev
channels:
    - pytorch
    - conda-forge
dependencies:
    - numpy==1.21.2
    - python==3.8.12
    - pip==21.3.1
    - pytorch==1.12.1
    - pytorch-lightning==1.5.10
    - torchvision==0.10.1
    - setuptools==57.4.0  #  The setuptools version must be <58.0.0 to accommodate pystruct
    - pip:
      - einops==0.6.0
      - flake8==3.8.4
      - flake8-docstrings==1.5.0
      - gitpython==3.1.13
      - h5py==2.10.0
      - scikit-learn==1.2.2
      - jupyter==1.0.0
      - matplotlib==3.6.2
      - mlflow==1.23.1
      - mock==4.0.3
      - opt_einsum==3.3.0
      - pynvml==8.0.4
      - pytest==6.2.5
      - pyyaml==5.4.1
      - recommonmark==0.7.1
      - segmentation-models-pytorch==0.2.0
      - orion==0.2.4.post1
      - rich==11.2.0
      - sphinx==7.1.2
      - sphinx-autoapi==3.0.0
      - sphinxcontrib-napoleon==0.7
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-katex==0.9.9
      - myst-parser==2.0.0
      - deepdiff==5.2.3
      - opencv-python==4.5.1.48
      - dash==2.9.1
      - ray==1.13.0
